### ISSUE TITLE
[feature request] 在 API 中添加跨域响应头

### ISSUE THREAD

**Issue by SerinaNya** [bs-community/yggdrasil-api#31]
_目前的 Yggdrasil API 没有跨域响应头，导致前端请求时报 `Network Error`_

希望 Yggdrasil API 在返回数据时添加上跨域头 `Access-Control-Allow-Origin: *`，以达到在前端直接请求 API 的目的

**Comment by g-plane** [comment]
这些 API 并不是给前端用的。

**Comment by SerinaNya** [comment]
但是没说不可以给前端用

**Comment by g-plane** [comment]
是没有说不可以，但这个特性是「不必要」的，加了也没带来多大的好处。

**Comment by SerinaNya** [comment]
会有什么坏处？

**Comment by g-plane** [comment]
没带来多大的好处 != 有坏处

**Comment by SerinaNya** [comment]
既然这样，那就加呗。
我就是你这个意思

**Comment by g-plane** [comment]
我是说，我不觉得有加的必要性。

**Comment by tnqzh123** [comment]
~~Mojang 也没有在官方的 Yggdrasil API 加 `Access-Control-Allow-Access`。~~

感觉这个更应该由皮肤站来做，有需要的皮肤站自己加上。

**Comment by SerinaNya** [comment]
那就当成兼容前端查询吧，CSL 的 API 不就有跨域头么

**Comment by g-plane** [comment]
并没有。

**Comment by SerinaNya** [comment]
宁好，有
![image](https://user-images.githubusercontent.com/34389622/78316767-0c95af00-7593-11ea-82c4-ccb131fc540f.png)

**Comment by g-plane** [comment]
您找演示站试试。

**Comment by SerinaNya** [comment]
> 您找演示站试试。

那个的确没有，但是你也知道，演示站过时了

**Comment by ShirasawaSama** [comment]
![image](https://user-images.githubusercontent.com/17093811/78317106-f89e7d00-7593-11ea-9e5c-c6dfe2263fab.png)
有是有, 但不是直接使用 `*` 的吧

**Comment by g-plane** [comment]
这与演示站过时与否没有关系，因为这部分代码基本没改变过，你自己搭建一个皮肤站就知道。

**Comment by SerinaNya** [comment]
:thinking: 我认为，加上这个头也不会有什么负面影响，反而能给一些（即使不多）开发者带来好处，何乐而不为？

**Comment by tnqzh123** [comment]
![image](https://user-images.githubusercontent.com/16630630/78317332-92fec080-7594-11ea-92a8-6c0eaa187b7a.png)

LittleSkin 也没有。

> 感觉这个更应该由皮肤站来做，有需要的皮肤站自己加上。

**Comment by g-plane** [comment]
解决这个问题的更好方法是自己搭建 API 代理。

> 加上这个头也不会有什么负面影响

这意味这个 API 可以被跨站请求，不能保证没有负面影响。

**Comment by SerinaNya** [comment]
> ![image](https://user-images.githubusercontent.com/16630630/78317332-92fec080-7594-11ea-92a8-6c0eaa187b7a.png)
> 
> LittleSkin 也没有。
> 
> > 感觉这个更应该由皮肤站来做，有需要的皮肤站自己加上。

<https://mcskin.littleservice.cn/Little_Qiu.json>

**Comment by SerinaNya** [comment]
> 解决这个问题的更好方法是自己搭建 API 代理。
> 
> > 加上这个头也不会有什么负面影响
> 
> 这意味这个 API 可以被跨站请求，不能保证没有负面影响。

可按照目前的认知来看，的确没有任何威胁

**Comment by g-plane** [comment]
> 解决这个问题的更好方法是自己搭建 API 代理。

**Comment by SerinaNya** [comment]
> 解决这个问题的更好方法是自己搭建 API 代理。

牺牲了速度，加大了成本。

**Comment by g-plane** [comment]
那您自行 fork 这个插件吧。（反正是开源的）

**Comment by g-plane** [comment]
其实也不需要 fork，自己写个插件，然后注册一个中间件并在中间件里修改头部同样是一个可行的办法。

**Comment by SerinaNya** [comment]
我去琢磨琢磨 :thinking:

**Comment by tnqzh123** [comment]
@jinzhijie 
> https://mcskin.littleservice.cn/Little_Qiu.json

![image](https://user-images.githubusercontent.com/16630630/78317854-00f7b780-7596-11ea-8b11-caeaafc0212d.png)

一样的。我没有故意加减 `Access-Control-Allow-Origin`。你也可以直接翻阅 BS 对应部分的代码。

**Comment by SerinaNya** [comment]
> 一样的。我没有故意加减 `Access-Control-Allow-Origin`。你也可以直接翻阅 BS 对应部分的代码。

![image](https://user-images.githubusercontent.com/34389622/78318106-8d09df00-7596-11ea-980e-38136474c3ad.png)

:thinking: @tnqzh123 
``` yaml
accept-ranges: bytes
access-control-allow-origin: *
cache-control: max-age=600
content-length: 220
content-type: application/json
date: Fri, 03 Apr 2020 02:32:21 GMT
etag: "5dd619f2-dc"
expires: Fri, 03 Apr 2020 02:42:21 GMT
last-modified: Thu, 21 Nov 2019 05:00:34 GMT
server: NWS_SP
status: 200
x-cache-lookup: Hit From Upstream
x-cache-lookup: Hit From Disktank3
x-daa-tunnel: hop_count=2
x-nws-log-uuid: 97c4779e-bd32-4ba2-a97c-0e8fde3e4ce4
x-nws-uuid-verify: 48c0ca4799af7b46a238ac70f15b855e
```
